# Generated by Django 3.2.4 on 2021-06-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturant',
            old_name='description',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='resturant',
            name='url',
        ),
    ]
